name: Gitops

on:
  push:
    branches: [ "**" ]
    tags: [ '**' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG_FOR_BRANCH: ${{ github.ref_name }}-${{ github.sha }}
  IMAGE_TAG_FOR_TAG: ${{ github.ref_name }}
  HELM_CHARTS_REPOSITORY: gitops-sample/helm-charts
  HELM_CHART_PATH: charts/application-01


jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG_FOR_BRANCH }},enable=${{ github.ref_type == 'branch' }}
            type=raw,value=${{ env.IMAGE_TAG_FOR_TAG }},enable=${{ github.ref_type == 'tag' }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm:

    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.HELM_CHARTS_REPOSITORY }}
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Change values.yaml for branch
        uses: mikefarah/yq@v4
        if: ${{ github.ref_type == 'branch' }}
        with:
          cmd: yq -i '.image.tag = "${{ env.IMAGE_TAG_FOR_BRANCH }}"' ${{ env.HELM_CHART_PATH }}/values.yaml

      - name: Change values.yaml for tag
        if: ${{ github.ref_type == 'tag' }}
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.image.tag = "${{ env.IMAGE_TAG_FOR_TAG }}"' ${{ env.HELM_CHART_PATH }}/values.yaml

      - name: Commit and push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git commit --message "edit .appVersion and .image.tag" ${{ env.HELM_CHART_PATH }}/Chart.yaml ${{ env.HELM_CHART_PATH }}/values.yaml
          git push
